export const fullFlagMap = {
  AF: "AF.svg",
  AX: "AX.svg",
  AL: "AL.svg",
  DZ: "DZ.svg",
  AS: "AS.svg",
  AD: "AD.svg",
  AO: "AO.svg",
  AI: "AI.svg",
  AQ: "AQ.svg",
  AG: "AG.svg",
  AR: "AR.svg",
  AM: "AM.svg",
  AW: "AW.svg",
  AU: "AU.svg",
  AT: "AT.svg",
  AZ: "AZ.svg",
  BS: "BS.svg",
  BH: "BH.svg",
  BD: "BD.svg",
  BB: "BB.svg",
  BY: "BY.svg",
  BE: "BE.svg",
  BZ: "BZ.svg",
  BJ: "BJ.svg",
  BM: "BM.svg",
  BT: "BT.svg",
  BO: "BO.svg",
  BQ: "BQ.svg",
  BA: "BA.svg",
  BW: "BW.svg",
  BV: "BV.svg",
  BR: "BR.svg",
  IO: "IO.svg",
  BN: "BN.svg",
  BG: "BG.svg",
  BF: "BF.svg",
  BI: "BI.svg",
  CV: "CV.svg",
  KH: "KH.svg",
  CM: "CM.svg",
  CA: "CA.svg",
  KY: "KY.svg",
  CF: "CF.svg",
  TD: "TD.svg",
  CL: "CL.svg",
  CN: "CN.svg",
  CX: "CX.svg",
  CC: "CC.svg",
  CO: "CO.svg",
  KM: "KM.svg",
  CG: "CG.svg",
  CD: "CD.svg",
  CK: "CK.svg",
  CR: "CR.svg",
  CI: "CI.svg",
  HR: "HR.svg",
  CU: "CU.svg",
  CW: "CW.svg",
  CY: "CY.svg",
  CZ: "CZ.svg",
  DK: "DK.svg",
  DJ: "DJ.svg",
  DM: "DM.svg",
  DO: "DO.svg",
  EC: "EC.svg",
  EG: "EG.svg",
  SV: "SV.svg",
  GQ: "GQ.svg",
  ER: "ER.svg",
  EE: "EE.svg",
  SZ: "SZ.svg",
  ET: "ET.svg",
  FK: "FK.svg",
  FO: "FO.svg",
  FJ: "FJ.svg",
  FI: "FI.svg",
  FR: "FR.svg",
  GF: "GF.svg",
  PF: "PF.svg",
  TF: "TF.svg",
  GA: "GA.svg",
  GM: "GM.svg",
  GE: "GE.svg",
  DE: "DE.svg",
  GH: "GH.svg",
  GI: "GI.svg",
  GR: "GR.svg",
  GL: "GL.svg",
  GD: "GD.svg",
  GP: "GP.svg",
  GU: "GU.svg",
  GT: "GT.svg",
  GG: "GG.svg",
  GN: "GN.svg",
  GW: "GW.svg",
  GY: "GY.svg",
  HT: "HT.svg",
  HM: "HM.svg",
  VA: "VA.svg",
  HN: "HN.svg",
  HK: "HK.svg",
  HU: "HU.svg",
  IS: "IS.svg",
  IN: "IN.svg",
  ID: "ID.svg",
  IR: "IR.svg",
  IQ: "IQ.svg",
  IE: "IE.svg",
  IM: "IM.svg",
  IL: "IL.svg",
  IT: "IT.svg",
  JM: "JM.svg",
  JP: "JP.svg",
  JE: "JE.svg",
  JO: "JO.svg",
  KZ: "KZ.svg",
  KE: "KE.svg",
  KI: "KI.svg",
  KP: "KP.svg",
  KR: "KR.svg",
  KW: "KW.svg",
  KG: "KG.svg",
  LA: "LA.svg",
  LV: "LV.svg",
  LB: "LB.svg",
  LS: "LS.svg",
  LR: "LR.svg",
  LY: "LY.svg",
  LI: "LI.svg",
  LT: "LT.svg",
  LU: "LU.svg",
  MO: "MO.svg",
  MG: "MG.svg",
  MW: "MW.svg",
  MY: "MY.svg",
  MV: "MV.svg",
  ML: "ML.svg",
  MT: "MT.svg",
  MH: "MH.svg",
  MQ: "MQ.svg",
  MR: "MR.svg",
  MU: "MU.svg",
  YT: "YT.svg",
  MX: "MX.svg",
  FM: "FM.svg",
  MD: "MD.svg",
  MC: "MC.svg",
  MN: "MN.svg",
  ME: "ME.svg",
  MS: "MS.svg",
  MA: "MA.svg",
  MZ: "MZ.svg",
  MM: "MM.svg",
  NA: "NA.svg",
  NR: "NR.svg",
  NP: "NP.svg",
  NL: "NL.svg",
  NC: "NC.svg",
  NZ: "NZ.svg",
  NI: "NI.svg",
  NE: "NE.svg",
  NG: "NG.svg",
  NU: "NU.svg",
  NF: "NF.svg",
  MK: "MK.svg",
  MP: "MP.svg",
  NO: "NO.svg",
  OM: "OM.svg",
  PK: "PK.svg",
  PW: "PW.svg",
  PS: "PS.svg",
  PA: "PA.svg",
  PG: "PG.svg",
  PY: "PY.svg",
  PE: "PE.svg",
  PH: "PH.svg",
  PN: "PN.svg",
  PL: "PL.svg",
  PT: "PT.svg",
  PR: "PR.svg",
  QA: "QA.svg",
  RE: "RE.svg",
  RO: "RO.svg",
  RU: "RU.svg",
  RW: "RW.svg",
  BL: "BL.svg",
  SH: "SH.svg",
  KN: "KN.svg",
  LC: "LC.svg",
  MF: "MF.svg",
  PM: "PM.svg",
  VC: "VC.svg",
  WS: "WS.svg",
  SM: "SM.svg",
  ST: "ST.svg",
  SA: "SA.svg",
  SN: "SN.svg",
  RS: "RS.svg",
  SC: "SC.svg",
  SL: "SL.svg",
  SG: "SG.svg",
  SX: "SX.svg",
  SK: "SK.svg",
  SI: "SI.svg",
  SB: "SB.svg",
  SO: "SO.svg",
  ZA: "ZA.svg",
  GS: "GS.svg",
  SS: "SS.svg",
  ES: "ES.svg",
  LK: "LK.svg",
  SD: "SD.svg",
  SR: "SR.svg",
  SJ: "SJ.svg",
  SE: "SE.svg",
  CH: "CH.svg",
  SY: "SY.svg",
  TW: "TW.svg",
  TJ: "TJ.svg",
  TZ: "TZ.svg",
  TH: "TH.svg",
  TL: "TL.svg",
  TG: "TG.svg",
  TK: "TK.svg",
  TO: "TO.svg",
  TT: "TT.svg",
  TN: "TN.svg",
  TR: "TR.svg",
  TM: "TM.svg",
  TC: "TC.svg",
  TV: "TV.svg",
  UG: "UG.svg",
  UA: "UA.svg",
  AE: "AE.svg",
  GB: "GB.svg",
  UM: "UM.svg",
  US: "US.svg",
  UY: "UY.svg",
  UZ: "UZ.svg",
  VU: "VU.svg",
  VE: "VE.svg",
  VN: "VN.svg",
  VG: "VG.svg",
  VI: "VI.svg",
  WF: "WF.svg",
  EH: "EH.svg",
  YE: "YE.svg",
  ZM: "ZM.svg",
  ZW: "ZW.svg",
  XX: "XX.svg",
};

export const baseUrl = "https://django-cloudrun-4fdxp3ewaq-ew.a.run.app/";
// export const baseUrl = "http://localhost:8000/"

export const countryListAlpha2 = {
  AF: "Afghanistan",
  AL: "Albania",
  DZ: "Algeria",
  AS: "American Samoa",
  AD: "Andorra",
  AO: "Angola",
  AI: "Anguilla",
  AQ: "Antarctica",
  AG: "Antigua and Barbuda",
  AR: "Argentina",
  AM: "Armenia",
  AW: "Aruba",
  AU: "Australia",
  AT: "Austria",
  AZ: "Azerbaijan",
  BS: "Bahamas (the)",
  BH: "Bahrain",
  BD: "Bangladesh",
  BB: "Barbados",
  BY: "Belarus",
  BE: "Belgium",
  BZ: "Belize",
  BJ: "Benin",
  BM: "Bermuda",
  BT: "Bhutan",
  BO: "Bolivia (Plurinational State of)",
  BQ: "Bonaire, Sint Eustatius and Saba",
  BA: "Bosnia and Herzegovina",
  BW: "Botswana",
  BV: "Bouvet Island",
  BR: "Brazil",
  IO: "British Indian Ocean Territory (the)",
  BN: "Brunei Darussalam",
  BG: "Bulgaria",
  BF: "Burkina Faso",
  BI: "Burundi",
  CV: "Cabo Verde",
  KH: "Cambodia",
  CM: "Cameroon",
  CA: "Canada",
  KY: "Cayman Islands (the)",
  CF: "Central African Republic (the)",
  TD: "Chad",
  CL: "Chile",
  CN: "China",
  CX: "Christmas Island",
  CC: "Cocos (Keeling) Islands (the)",
  CO: "Colombia",
  KM: "Comoros (the)",
  CD: "Congo (the Democratic Republic of the)",
  CG: "Congo (the)",
  CK: "Cook Islands (the)",
  CR: "Costa Rica",
  HR: "Croatia",
  CU: "Cuba",
  CW: "Curaçao",
  CY: "Cyprus",
  CZ: "Czechia",
  CI: "Côte d'Ivoire",
  DK: "Denmark",
  DJ: "Djibouti",
  DM: "Dominica",
  DO: "Dominican Republic (the)",
  EC: "Ecuador",
  EG: "Egypt",
  SV: "El Salvador",
  GQ: "Equatorial Guinea",
  ER: "Eritrea",
  EE: "Estonia",
  SZ: "Eswatini",
  ET: "Ethiopia",
  FK: "Falkland Islands (the) [Malvinas]",
  FO: "Faroe Islands (the)",
  FJ: "Fiji",
  FI: "Finland",
  FR: "France",
  GF: "French Guiana",
  PF: "French Polynesia",
  TF: "French Southern Territories (the)",
  GA: "Gabon",
  GM: "Gambia (the)",
  GE: "Georgia",
  DE: "Germany",
  GH: "Ghana",
  GI: "Gibraltar",
  GR: "Greece",
  GL: "Greenland",
  GD: "Grenada",
  GP: "Guadeloupe",
  GU: "Guam",
  GT: "Guatemala",
  GG: "Guernsey",
  GN: "Guinea",
  GW: "Guinea-Bissau",
  GY: "Guyana",
  HT: "Haiti",
  HM: "Heard Island and McDonald Islands",
  VA: "Holy See (the)",
  HN: "Honduras",
  HK: "Hong Kong",
  HU: "Hungary",
  IS: "Iceland",
  IN: "India",
  ID: "Indonesia",
  IR: "Iran (Islamic Republic of)",
  IQ: "Iraq",
  IE: "Ireland",
  IM: "Isle of Man",
  IL: "Israel",
  IT: "Italy",
  JM: "Jamaica",
  JP: "Japan",
  JE: "Jersey",
  JO: "Jordan",
  KZ: "Kazakhstan",
  KE: "Kenya",
  KI: "Kiribati",
  KP: "Korea (the Democratic People's Republic of)",
  KR: "Korea (the Republic of)",
  KW: "Kuwait",
  KG: "Kyrgyzstan",
  LA: "Lao People's Democratic Republic (the)",
  LV: "Latvia",
  LB: "Lebanon",
  LS: "Lesotho",
  LR: "Liberia",
  LY: "Libya",
  LI: "Liechtenstein",
  LT: "Lithuania",
  LU: "Luxembourg",
  MO: "Macao",
  MG: "Madagascar",
  MW: "Malawi",
  MY: "Malaysia",
  MV: "Maldives",
  ML: "Mali",
  MT: "Malta",
  MH: "Marshall Islands (the)",
  MQ: "Martinique",
  MR: "Mauritania",
  MU: "Mauritius",
  YT: "Mayotte",
  MX: "Mexico",
  FM: "Micronesia (Federated States of)",
  MD: "Moldova (the Republic of)",
  MC: "Monaco",
  MN: "Mongolia",
  ME: "Montenegro",
  MS: "Montserrat",
  MA: "Morocco",
  MZ: "Mozambique",
  MM: "Myanmar",
  NA: "Namibia",
  NR: "Nauru",
  NP: "Nepal",
  NL: "Netherlands (the)",
  NC: "New Caledonia",
  NZ: "New Zealand",
  NI: "Nicaragua",
  NE: "Niger (the)",
  NG: "Nigeria",
  NU: "Niue",
  NF: "Norfolk Island",
  MP: "Northern Mariana Islands (the)",
  NO: "Norway",
  OM: "Oman",
  PK: "Pakistan",
  PW: "Palau",
  PS: "Palestine, State of",
  PA: "Panama",
  PG: "Papua New Guinea",
  PY: "Paraguay",
  PE: "Peru",
  PH: "Philippines (the)",
  PN: "Pitcairn",
  PL: "Poland",
  PT: "Portugal",
  PR: "Puerto Rico",
  QA: "Qatar",
  MK: "Republic of North Macedonia",
  RO: "Romania",
  RU: "Russian Federation (the)",
  RW: "Rwanda",
  RE: "Réunion",
  BL: "Saint Barthélemy",
  SH: "Saint Helena, Ascension and Tristan da Cunha",
  KN: "Saint Kitts and Nevis",
  LC: "Saint Lucia",
  MF: "Saint Martin (French part)",
  PM: "Saint Pierre and Miquelon",
  VC: "Saint Vincent and the Grenadines",
  WS: "Samoa",
  SM: "San Marino",
  ST: "Sao Tome and Principe",
  SA: "Saudi Arabia",
  SN: "Senegal",
  RS: "Serbia",
  SC: "Seychelles",
  SL: "Sierra Leone",
  SG: "Singapore",
  SX: "Sint Maarten (Dutch part)",
  SK: "Slovakia",
  SI: "Slovenia",
  SB: "Solomon Islands",
  SO: "Somalia",
  ZA: "South Africa",
  GS: "South Georgia and the South Sandwich Islands",
  SS: "South Sudan",
  ES: "Spain",
  LK: "Sri Lanka",
  SD: "Sudan (the)",
  SR: "Suriname",
  SJ: "Svalbard and Jan Mayen",
  SE: "Sweden",
  CH: "Switzerland",
  SY: "Syrian Arab Republic",
  TW: "Taiwan",
  TJ: "Tajikistan",
  TZ: "Tanzania, United Republic of",
  TH: "Thailand",
  TL: "Timor-Leste",
  TG: "Togo",
  TK: "Tokelau",
  TO: "Tonga",
  TT: "Trinidad and Tobago",
  TN: "Tunisia",
  TR: "Turkey",
  TM: "Turkmenistan",
  TC: "Turks and Caicos Islands (the)",
  TV: "Tuvalu",
  UG: "Uganda",
  UA: "Ukraine",
  AE: "United Arab Emirates (the)",
  GB: "United Kingdom of Great Britain and Northern Ireland (the)",
  UM: "United States Minor Outlying Islands (the)",
  US: "United States of America (the)",
  UY: "Uruguay",
  UZ: "Uzbekistan",
  VU: "Vanuatu",
  VE: "Venezuela (Bolivarian Republic of)",
  VN: "Viet Nam",
  VG: "Virgin Islands (British)",
  VI: "Virgin Islands (U.S.)",
  WF: "Wallis and Futuna",
  EH: "Western Sahara",
  YE: "Yemen",
  ZM: "Zambia",
  ZW: "Zimbabwe",
  AX: "Åland Islands",
};
